### ISSUE TITLE
Model code optimization

### ISSUE THREAD

**Issue by AndreyK641** [SorourMo/Cloud-Net#3]
Hello!
In the functions improve_ff_block is it correct to replace code

```python
for ix in range(1):
    if ix == 0:
        x1 = input_tensor1
    x1 = concatenate([x1, input_tensor1], axis=3)
x1 = MaxPooling2D(pool_size=(2, 2))(x1)
```

by 

```python
x1 = MaxPooling2D(pool_size=(2, 2))(input_tensor1)
x1 = concatenate([x1, x1], axis=3)
```

and

```python
for ix in range(3):
    if ix == 0:
        x2 = input_tensor2
    x2 = concatenate([x2, input_tensor2], axis=3)
 x2 = MaxPooling2D(pool_size=(4, 4))(x2)
```

by

```python
x2 = x = MaxPooling2D(pool_size=(4, 4))(input_tensor2)
 for ix in range(3):
    x2 = concatenate([x2, x], axis=3)
```

?

I think it is possible to apply this approach for x3 and x4 calculation.

**Comment by Silengcewang** [comment]
> Hello!
> In the functions improve_ff_block is it correct to replace code
> 
> ```python
> for ix in range(1):
>     if ix == 0:
>         x1 = input_tensor1
>     x1 = concatenate([x1, input_tensor1], axis=3)
> x1 = MaxPooling2D(pool_size=(2, 2))(x1)
> ```
> 
> by
> 
> ```python
> x1 = MaxPooling2D(pool_size=(2, 2))(input_tensor1)
> x1 = concatenate([x1, x1], axis=3)
> ```
> 
> and
> 
> ```python
> for ix in range(3):
>     if ix == 0:
>         x2 = input_tensor2
>     x2 = concatenate([x2, input_tensor2], axis=3)
>  x2 = MaxPooling2D(pool_size=(4, 4))(x2)
> ```
> 
> by
> 
> ```python
> x2 = x = MaxPooling2D(pool_size=(4, 4))(input_tensor2)
>  for ix in range(3):
>     x2 = concatenate([x2, x], axis=3)
> ```
> 
> ?
> 
> I think it is possible to apply this approach for x3 and x4 calculation.

Hello! I have a question that why the evaluation index of same method  in the cloudnet and cloudnet++ are different

**Comment by SorourMo** [comment]
Please refer to https://github.com/SorourMo/38-Cloud-A-Cloud-Segmentation-Dataset/issues/7

**Comment by SorourMo** [comment]
> Hello!
> In the functions improve_ff_block is it correct to replace code
> 
> ```python
> for ix in range(1):
>     if ix == 0:
>         x1 = input_tensor1
>     x1 = concatenate([x1, input_tensor1], axis=3)
> x1 = MaxPooling2D(pool_size=(2, 2))(x1)
> ```
> 
> by
> 
> ```python
> x1 = MaxPooling2D(pool_size=(2, 2))(input_tensor1)
> x1 = concatenate([x1, x1], axis=3)
> ```
> 
> and
> 
> ```python
> for ix in range(3):
>     if ix == 0:
>         x2 = input_tensor2
>     x2 = concatenate([x2, input_tensor2], axis=3)
>  x2 = MaxPooling2D(pool_size=(4, 4))(x2)
> ```
> 
> by
> 
> ```python
> x2 = x = MaxPooling2D(pool_size=(4, 4))(input_tensor2)
>  for ix in range(3):
>     x2 = concatenate([x2, x], axis=3)
> ```
> 
> ?
> 
> I think it is possible to apply this approach for x3 and x4 calculation.

Yes, they are equivalent.
